luci-app-adblock-plus:update to 1.0-8

diff --git a/zxlhhyccc/luci-app-adblock-plus/root/usr/share/adblock/addown b/zxlhhyccc/luci-app-adblock-plus/root/usr/share/adblock/addown
--- a/zxlhhyccc/luci-app-adblock-plus/root/usr/share/adblock/addown
+++ b/zxlhhyccc/luci-app-adblock-plus/root/usr/share/adblock/addown
@@ -9,25 +9,31 @@ A=0
 B=/tmp/adblock
 C=/tmp/adupdate.log
 D="date +'%Y-%m-%d %H:%M:%S'"
-E="curl -Lfso"
-F="Download Adblock Plus Rules"
-G="Download Subscribe Rules"
+E="Download Adblock Plus Rules"
 
 if [ "$2" = 1 ];then
 	mkdir -p $B
-	echo "`eval $D` [$F]" > $C
-	while ! $E $B/adblock.conf https://cdn.jsdelivr.net/gh/small-5/ad-rules/dnsmasq.adblock;do
+	echo "`eval $D` [Check network status]" > $C
+	while ! curl -so /dev/null -m 3 www.baidu.com;do
+		cat $C | grep -q Wait || echo "`eval $D` [Wait for network to connect]" >> $C
 		sleep 2
 	done
-	echo "`eval $D` [$F Successful]" >> $C
+	echo "`eval $D` [Check network status Successful]" >> $C
+	echo "`eval $D` [$E]" >> $C
+	X=1
+	while ! curl --connect-timeout 5 -m 20 -Lfso $B/adblock.conf https://cdn.jsdelivr.net/gh/small-5/ad-rules/dnsmasq.adblock;do
+		[ $X -ge 20 ] && A=1 && return || let X++
+		sleep 2
+	done
+	echo "`eval $D` [$E Successful]" >> $C
 	for i in $(cat /etc/adblock/white.list);do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $B/adblock.conf;done
 fi
 
-if [ "$3" = 1 -a $A != 1 ];then
-	echo "`eval $D` [$G]" >> $C
+if [ "$3" = 1 -a $A = 0 ];then
+	echo "`eval $D` [Download Subscribe Rules]" >> $C
 	/usr/share/adblock/adblock addown >> $C
 fi
 
-[ $A = 1 ] || (echo "`eval $D` [Start Adblock Plus+]" >> $C;echo `eval $D` > $B/adblock.updated)
+[ $A = 1 ] && echo "`eval $D` [$E Failed]" >> $C || (echo "`eval $D` [Start Adblock Plus+]" >> $C;echo "`eval $D`" > $B/adblock.updated)
 rm -f $LOCK
 /etc/init.d/adblock start &
