luci-app-bypass:update@20210114

diff --git a/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch b/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch
--- a/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch
+++ b/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch
@@ -17,14 +17,17 @@ uci_get_by_type(){
 get_ip(){
 	if ! echo $ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
 		r=1
-		while ! nslookup $ip >/dev/null 2>&1;do
+		while ! nslookup $ip 127.0.0.1#5336 >/dev/null 2>&1;do
 			[ $r -ge 10 ] && return 1 || let r++
 			sleep 1
 		done
-		ip=$(nslookup $ip 127.0.0.1#5336 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$");i=$?
+		if ! ip=$(nslookup $ip 127.0.0.1#5336 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"); then
+			echo "$(eval $DATE) By-Switch: Unable to get server address.Check domain name!" >>$L
+			return 1
+		fi
 		ip=$(echo "$ip" | sed -n 1p)
+		return 0
 	fi
-	return $i
 }
 
 f_bin(){
@@ -146,6 +149,7 @@ curl_check(){
 		[ $r -ge 10 ] && return 1 || let r++
 		sleep 1
 	done
+	/usr/share/bypass/by-rules -f
 	curl -x socks5h://$IP:$lport $param -so /dev/null --connect-timeout $time_b https://www.google.com;i=$?
 	kill -9 $(ps -w | grep $J | grep -v grep | awk '{print$1}') 2>/dev/null
 	[ $i = 0 ] || echo "`eval $D` By-Switch : Server : $($UCI$1.alias || uci_get_by_name $1 server) cURL check error, Try to switch another server." >> $L
