luci-app-bypass:bump to 1.2-44

diff --git a/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch b/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch
--- a/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch
+++ b/zxlhhyccc/luci-app-bypass/root/usr/share/bypass/by-switch
@@ -15,16 +15,16 @@ uci_get_by_type(){
 }
 
 get_ip(){
-	if ! echo $ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
+	if ! echo $server | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
 		r=1
-		while ! nslookup $ip 127.0.0.1#5336 >/dev/null 2>&1;do
-			[ $r -ge 10 ] && return 1 || let r++
+		while ! ip=$(nslookup $server 127.0.0.1#5336 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$");do
+		if ! ip=$(nslookup $server 223.5.5.5 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"); then
+			[ $r -ge 10 ] && echo "$(eval $DATE) By-Switch: Unable to get $server address Check domain name!" >>$L; return 1 || let r++
 			sleep 1
-		done
-		if ! ip=$(nslookup $ip 127.0.0.1#5336 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"); then
-			echo "$(eval $DATE) By-Switch: Unable to get $ip address. Check domain name!" >>$L
-			return 1
+		else
+			break
 		fi
+		done
 		ip=$(echo "$ip" | sed -n 1p)
 		return 0
 	fi
@@ -157,7 +157,7 @@ curl_check(){
 }
 
 test_proxy(){
-	ip=$(uci_get_by_name $1 server)
+	server=$(uci_get_by_name $1 server)
 	get_ip || return 1
 	port=$(uci_get_by_name $1 server_port)
 	ipset add ss_spec_wan_ac $ip 2>/dev/null
@@ -189,7 +189,7 @@ select_proxy(){
 	for i in $(seq $c $b);do
 		d=$(echo "$a" | sed 's/.*\.\(.*\)=.*/\1/' | sed -n ${i}p)
 		([ $d = $SERVER_B ] || [ $(uci_get_by_name $d switch_enable 0) != 1 ]) && continue
-		ip=$(uci_get_by_name $d server)
+		server=$(uci_get_by_name $d server)
 		get_ip || continue
 		port=$(uci_get_by_name $d server_port)
 		ipset add ss_spec_wan_ac $ip 2>/dev/null
@@ -222,12 +222,12 @@ while :;do
 	if [ $SERVER_A != $SERVER_B ];then
 		echo "`eval $D` By-Switch : Current server : $($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server) is not main server : $($UCI$SERVER_A.alias || uci_get_by_name $SERVER_A server).Try to switch back." >> $L
 		if test_proxy $SERVER_A;then
-			echo "`eval $D` By-Switch : Main server is available.Switch to main server." >> $L
+			echo "`eval $D` By-Switch : Main server is available. Switch to main server." >> $L
 			SERVER_B=$SERVER_A
 			switch_proxy
 			continue
 		else
-			echo "`eval $D` By-Switch : Main server is not available.Continue using current server." >> $L
+			echo "`eval $D` By-Switch : Main server is not available. Continue using current server." >> $L
 		fi
 	fi
 	check_proxy
