luci-app-wechatpush: update to 3.3.2

diff --git a/ctcgfw/luci-app-wechatpush/root/usr/share/wechatpush/wechatpush b/ctcgfw/luci-app-wechatpush/root/usr/share/wechatpush/wechatpush
--- a/ctcgfw/luci-app-wechatpush/root/usr/share/wechatpush/wechatpush
+++ b/ctcgfw/luci-app-wechatpush/root/usr/share/wechatpush/wechatpush
@@ -57,7 +57,7 @@ function read_config(){
 	done
 	( opkg list-installed|grep -w -q ^firewall4 ) && nftables_version="true"
 	dir="/tmp/wechatpush/" && mkdir -p ${dir} && mkdir -p ${dir}/client
-	tempjsonpath="/tmp/wechatpush/temp.json"
+	tempjsonpath="${dir}temp.json"
 	ip_blacklist_path="/usr/share/wechatpush/api/ip_blacklist"
 	oui_base="${dir}oui_base.txt"
 	debuglevel=`echo "$debuglevel"` && [ -z "$debuglevel" ] && logfile="/dev/null" || logfile="${dir}wechatpush.log"
@@ -80,7 +80,7 @@ function read_config(){
 	[ -z "$login_ip_white_timeout" ] && login_ip_white_timeout="600"
 	[ "$iw_version" ] && wlan_interface=`iw dev 2>/dev/null|grep Interface|awk '{print $2}'` >/dev/null 2>&1
 	[ -z "$server_port" ] && server_port="22"
-	output_dir="/tmp/wechatpush/json_output"
+	output_dir="${dir}json_output"
 	mkdir -p "$output_dir"
 	if ( echo "$lite_enable"|grep -q "content" ); then
 		str_title_start="" && str_title_end="" && str_splitline="" && str_linefeed="" && str_tab=""
@@ -121,10 +121,15 @@ function init(){
 	[ -n "$notification_load" ] && [ -n "$cpu_load_threshold" ] && local cpu_fuzai=`cat /proc/loadavg|awk '{print $1}'` 2>/dev/null || local cpu_fuzai="null"
 	[ -z "$cpu_fuzai" ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】无法读取设备负载，请检查命令" >> ${logfile}
 
-	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv4"
-	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv6"
 	[ -n "$login_web_black" ] && [ "$login_web_black" -eq "1" ] && init_ip_black "ipv4"
 	[ -n "$login_web_black" ] && [ "$login_web_black" -eq "1" ] && init_ip_black "ipv6"
+	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv4"
+	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv6"
+
+	tmp_ip_list=`echo "$login_ip_white_list"|grep -v "^$"|sort -u`
+	while IFS= read -r tmp_ip; do
+		[ -n "$tmp_ip" ] && add_ip_white "$tmp_ip" "0"
+	done <<< "$tmp_ip_list"
 	set_ip_black
 	return 0
 }
@@ -372,7 +377,7 @@ function soc_temp(){
 		# AMD
 		local sensor_field2='["zenpower-pci-00c3"]["Tctl"]["temp1_input"]'
 		local sensor_field3='["k10temp-pci-00c3"]["Tctl"]["temp1_input"]'
-		eval "${1}sensors -j 2>/dev/null" | jq -r "
+		eval "${1} sensors -j 2>/dev/null" | jq -r "
 		if .${sensor_field1} != null then
 		  .${sensor_field1}
 		elif .${sensor_field2} != null then
@@ -385,7 +390,7 @@ function soc_temp(){
 		"
 	}
 
-	[ ! -z "$server_host" ] && ssh_command="ssh -o StrictHostKeyChecking=yes -o BatchMode=yes -i /root/.ssh/id_rsa root@${server_host} -p ${server_port} "
+	[ ! -z "$server_host" ] && ssh_command="ssh -o StrictHostKeyChecking=yes -o BatchMode=yes -i /root/.ssh/id_rsa root@${server_host} -p ${server_port}"
 	temperature=$(getsensors "$ssh_command" 2>/dev/null)
 	# 通用（只能取最高温度，不一定是 CPU，特殊设备自行修改）
 	# 将 grep °C 改为温度所在行的特别字符串，如 grep Core 0 等，就可以指定设备了
@@ -500,7 +505,7 @@ function time_for_humans {
 	fi
 }
 
-# 计算字符真实长度
+# 计算字符显示宽度
 function length_str {
 	[ ! "$1" ] && return
 	
@@ -633,8 +638,8 @@ function cron(){
 
 	# 重置流量
 	if [ ! -z "$reset_regularly" ] && [ "$reset_regularly" -eq "1" ]; then
-		crontab -l 2>/dev/null > conf && echo -e "0 0 * * * rm /tmp/wechatpush/usage.db >/dev/null 2>&1" >> conf && crontab conf && rm -f conf >/dev/null 2>&1
-		crontab -l 2>/dev/null > conf && echo -e "0 0 * * * rm /tmp/wechatpush/usage6.db >/dev/null 2>&1" >> conf && crontab conf && rm -f conf >/dev/null 2>&1
+		crontab -l 2>/dev/null > conf && echo -e "0 0 * * * rm ${dir}usage.db >/dev/null 2>&1" >> conf && crontab conf && rm -f conf >/dev/null 2>&1
+		crontab -l 2>/dev/null > conf && echo -e "0 0 * * * rm ${dir}usage6.db >/dev/null 2>&1" >> conf && crontab conf && rm -f conf >/dev/null 2>&1
 	fi
 
 	# 定时发送
@@ -729,10 +734,10 @@ function geterrdevicealiases(){
 	if [ ! -z "$sheep_starttime" ] && [ "$((`date +%s`-$sheep_starttime))" -ge "3600" ]; then
 		> ${dir}sheep_usage
 		local MACLIST=`echo "$unattended_device_aliases"|grep -v "^$"|sort -u`
-		for mac in $MACLIST; do
+		while IFS= read -r mac; do
 			[ ! -z "$mac" ] && local tmptotal=`usage get ${mac} bytes`
 			[ ! -z "$tmptotal" ] && awk 'BEGIN{printf "%.0f\n",'$tmptotal'/'204800'}' 2>/dev/null >> ${dir}sheep_usage
-		done
+		done <<< "$MACLIST"
 		old_sheep_usage=`cat ${dir}old_sheep_usage` 2>/dev/null
 		sheep_usage=`cat ${dir}sheep_usage` 2>/dev/null
 		[ "$old_sheep_usage" == "$sheep_usage" ] && [ -z "$sheep_nousage_starttime" ] && sheep_nousage_starttime=`date +%s`
@@ -1087,25 +1092,132 @@ function cputop(){
 	[ ! -z "$1" ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！警报！！】 CPU 占用前三: ${logtop}" >> ${logfile}
 }
 
+# 检测硬盘状态
+function get_disk() {
+	mkdir -p "${dir}disk_info"
+	local_disk_names=()
+	pve_disk_names=()
+
+	# 查询本地硬盘名
+	local_disk_names=($(lsblk | awk '$NF=="disk" {print $1}' | sort -u))
+	local_disk_tags=($(for _ in "${local_disk_names[@]}"; do echo "local"; done))
+
+	# 查询远程硬盘名
+	if [ -n "$server_host" ]; then
+		ssh_command="ssh -o StrictHostKeyChecking=yes -o BatchMode=yes -i /root/.ssh/id_rsa root@${server_host} -p ${server_port}"
+		pve_disk_names=($(eval ${ssh_command} lsblk | awk '$NF=="disk" {print $1}' | sort -u))
+		pve_disk_tags=($(for _ in "${pve_disk_names[@]}"; do echo "pve"; done))
+	fi
+
+	# 合并本地和远程硬盘名及标记
+	all_disk_names=("${local_disk_names[@]}" "${pve_disk_names[@]}")
+	all_disk_tags=("${local_disk_tags[@]}" "${pve_disk_tags[@]}")
+
+	for i in "${!all_disk_names[@]}"; do
+		tmp_name=${all_disk_names[i]}
+		tmp_tag=${all_disk_tags[i]}
+		error_pattern="No such device|Unable to detect device type|Unknown USB bridge|QEMU HARDDISK"
+		unset tmp_command disk_type disk_err
+
+		# 判断硬盘类型
+		if [ "$tmp_tag" == "pve" ]; then
+			tmp_command="$ssh_command"
+			disk_type="_pve"
+		fi
+		file_path="${dir}disk_info/${tmp_name}${disk_type}"
+
+		# 如果不能获取值，使用分区名重试（因为不清楚是 OpenWrt 的原因还是 smartctl 版本的原因，使用出错重试的方式）
+		eval ${tmp_command} smartctl -i -n standby "/dev/${tmp_name}" | grep -qE "$error_pattern" && {
+			tmp_name=$(df -h | awk "/^\\/dev\\/${tmp_name}/ {print \$1}" | awk -F '/' '{print $NF}' | head -n1)
+			[ -z "$tmp_name" ] && continue
+		}
+
+		# 手上的硬盘不能休眠，不确定命令是否会唤醒硬盘，每天只运行一次
+		last_disk_time=$(date -r "${file_path}" +%s 2>/dev/null) || last_disk_time=0
+
+		if [ $(( $(date +%s) - $last_disk_time )) -gt 86000 ]; then
+			disk_info=$(eval ${tmp_command} smartctl -i -n standby "/dev/${tmp_name}")
+			echo "$disk_info" | grep -qE "$error_pattern" && {
+				continue
+			} || \
+			echo "$disk_info" | grep -q "STANDBY" && {
+				echo "$disk_info" > "${file_path}"
+			} || \
+			eval ${tmp_command} smartctl -a -j /dev/${tmp_name} > ${file_path}
+		fi
+
+		# 硬盘状态
+		if [ -f "${file_path}" ] && ( ! cat "${file_path}" | grep -q -v "STANDBY" ); then
+			disk_name=$(awk '/Device Model/{print $NF}' "$file_path")
+			[[ -n $disk_name && $disk_name != null && $disk_name != 0 ]] && {
+				disk_name=$(cut_str "$disk_name" "20")
+				disk_name="${disk_name}_$(eval ${tmp_command} lsblk -o NAME,SIZE | awk "/^${all_disk_names[i]}/ {print \$NF}")"
+			}
+			printf "${str_linefeed}${str_title_start} 硬盘名称：${disk_name}${disk_type}${str_title_end}${str_linefeed}${str_tab}硬盘休眠中" >> "$output_dir/get_disk"
+		elif [ -f "${file_path}" ]; then
+			# 硬盘名称
+			disk_name=$(jq -r .model_name ${file_path})
+			[[ -n $disk_name && $disk_name != null && $disk_name != 0 ]] && {
+				disk_name=$(cut_str "$disk_name" "20")
+				disk_name="${disk_name}_$(eval ${tmp_command} lsblk -o NAME,SIZE | awk "/^${all_disk_names[i]}/ {print \$NF}")"
+			}
+			printf "${str_linefeed}${str_title_start} 硬盘名称：${disk_name}${disk_type}${str_title_end}" >> "$output_dir/get_disk"
+			# 硬盘温度
+			disk_temp=$(jq -r .temperature.current ${file_path})
+			[[ -n $disk_temp && $disk_temp != null && $disk_temp != 0 ]] && printf "${str_linefeed}${str_tab}硬盘温度：${disk_temp}℃" >> "$output_dir/get_disk"
+			# 通电时间
+			disk_time=$(jq -r .power_on_time.hours ${file_path})
+			[[ -n $disk_time && $disk_time != null ]] && printf "${str_linefeed}${str_tab}通电时间：${disk_time}h" >> "$output_dir/get_disk"
+			# 空间使用
+			disk_use=$(eval ${tmp_command} lsblk -o NAME,FSUSE%,TYPE | awk -v part_name="${all_disk_names[i]}" '$NF == "part" && $1 ~ part_name && NF > 2 {sub(".*" part_name, part_name, $1); printf "%s: %s  ", $1, $2} END {print ""}')
+			[ -n "$disk_use" ] && [ -n "${disk_use// }" ] && echo -e -n "${str_linefeed}${str_tab}空间使用：${disk_use}" >> "$output_dir/get_disk"
+			# 寿命使用
+			disk_health=$(jq -r .nvme_smart_health_information_log.percentage_used ${file_path})
+			[[ -n $disk_health && $disk_health != null ]] && echo -e -n "${str_linefeed}${str_tab}寿命使用：${disk_health}%" >> "$output_dir/get_disk"
+			# 错误日志
+			disk_log_err=$(jq -r .ata_smart_error_log.summary.count ${file_path})
+			[[ -n $disk_log_err && $disk_log_err != null && $disk_log_err != 0 ]] && disk_err="true" && printf "${str_linefeed}${str_tab}错误日志：${disk_log_err}" >> "$output_dir/get_disk"
+			# 自检错误
+			disk_test_err=$(jq -r .ata_smart_self_test_log.standard.error_count_total ${file_path})
+			[[ -n $disk_test_err && $disk_test_err != null && $disk_test_err != 0 ]] && disk_err="true" && printf "${str_linefeed}${str_tab}自检错误：${disk_test_err}" >> "$output_dir/get_disk"
+			# 0E 错误
+			disk_0e_err=$(jq -r .nvme_smart_health_information_log.media_errors ${file_path})
+			[[ -n $disk_0e_err && $disk_0e_err != null && $disk_0e_err != 0 ]] && disk_err="true" && printf "${str_linefeed}${str_tab}0E 错误：${disk_0e_err}" >> "$output_dir/get_disk"
+			# 整体健康
+			smart_status=$(jq -r .smart_status.passed ${file_path})
+			[[ -n $smart_status && $smart_status != null && $smart_status != "true" ]] && {
+				echo -e -n "${str_linefeed}${str_tab}${str_title_start}硬盘整体健康评估不通过!!!${str_title_end}" >> "$output_dir/get_disk"
+				disk_err="true"
+			}
+			[ -n "$disk_err" ] && echo -e -n "${str_linefeed}${str_tab}${str_title_start}硬盘存在错误，请及时备份数据!!!${str_title_end}" >> "$output_dir/get_disk"
+		fi
+	done
+}
+
+
 # 查询 IP 归属地
 function get_ip_attribution(){
 	ip="$1"
 	[ -f ${dir}ipAddress ] && ( cat ${dir}ipAddress|grep -q -w -i "$ip" ) && echo "本地网络" && return
 	ip_attribution_urls=$(cat /usr/share/wechatpush/api/ip_attribution.list)
-	for ip_attribution_command in ${ip_attribution_urls}; do
+	while IFS= read -r ip_attribution_command; do
 		login_ip_attribution=$(eval "$ip_attribution_command" 2>/dev/null)
 		[ "$login_ip_attribution" == "null" ] && unset login_ip_attribution
 		[ -n "$login_ip_attribution" ] && break
-	done
+	done <<< "$ip_attribution_urls"
 	echo "$login_ip_attribution"
 }
 
 # 登录提醒通知
 function login_send(){
-	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv4"
-	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv6"
 	[ -n "$login_web_black" ] && [ "$login_web_black" -eq "1" ] && init_ip_black "ipv4"
 	[ -n "$login_web_black" ] && [ "$login_web_black" -eq "1" ] && init_ip_black "ipv6"
+	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv4"
+	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] && init_ip_white "ipv6"
+	tmp_ip_list=`echo "$login_ip_white_list"|grep -v "^$"|sort -u`
+	while IFS= read -r tmp_ip; do
+		[ -n "$tmp_ip" ] && add_ip_white "$tmp_ip" "0"
+	done <<< "$tmp_ip_list"
 	[ -z "$web_logged" ] && [ -z "$ssh_logged" ] && [ -z "$web_login_failed" ] && [ -z "$ssh_login_failed" ] && return
 	set_ip_black
 	sys_log=$(logread notice)
@@ -1221,14 +1333,15 @@ function login_send(){
 # 添加白名单，懒得写删除项和信息显示了，纯粹就是懒
 function add_ip_white() {
 	[ -n "$port_knocking_enable" ] && [ "$port_knocking_enable" -eq "1" ] || return
+	[ -z "$2" ] && timeout=$login_ip_white_timeout || timeout=$2
 	# 检查 IP 版本
 	( echo "$1"|grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$' ) && local ipset_name="wechatpush_whitelist"
 	( echo "$1"|grep -Eq '^([\da-fA-F0-9]{1,4}(:{1,2})){1,15}[\da-fA-F0-9]{1,4}$' ) && local ipset_name="wechatpush_whitelistv6"
 	[ -z "$ipset_name" ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【!!!】白名单添加失败，IP 格式错误" >> ${logfile} && return
 
 	[ -n "$nftables_version" ] && nft delete element inet fw4 $ipset_name { $1 } >/dev/null 2>&1
-	[ -n "$nftables_version" ] && nft add element inet fw4 $ipset_name { $1 expires ${login_ip_white_timeout}s } && return #没找到刷新时间的命令，删除再添加
-	ipset -exist add $ipset_name $1 timeout $login_ip_white_timeout
+	[ -n "$nftables_version" ] && nft add element inet fw4 $ipset_name { $1 expires ${timeout}s } && return #没找到刷新时间的命令，删除再添加
+	ipset -exist add $ipset_name $1 timeout $timeout
 }
 
 # 初始化白名单
@@ -1273,7 +1386,7 @@ function init_ip_white() {
 	fi
 	unset handle
 	# 端口转发
-	for port_forward in `echo "$login_port_forward_list"`; do
+	while IFS= read -r port_forward; do
 		port_forward=`echo "$port_forward"|sed 's/,/ /g'` 2>/dev/null
 		[ `echo $port_forward| awk -F" " '{print NF}'` -ne "4" ] && continue
 		local src_ip=`echo ${port_forward}|awk '{print $1}'`
@@ -1287,7 +1400,7 @@ function init_ip_white() {
 			${ip_version}tables -t nat -C PREROUTING -m set --match-set $ipset_name src -p tcp --dport $src_port -j DNAT --to-destination "$dst_ip:$dst_port" >/dev/null 2>&1 || ${ip_version}tables -t nat -I PREROUTING -m set --match-set $ipset_name src -p tcp --dport $src_port -j DNAT --to-destination "$dst_ip:$dst_port" >/dev/null 2>&1
 			${ip_version}tables -t nat -C POSTROUTING -m set --match-set $ipset_name src -p tcp -d $dst_ip --dport $dst_port -j SNAT --to-source $src_ip >/dev/null 2>&1 || ${ip_version}tables -t nat -I POSTROUTING -m set --match-set $ipset_name src -p tcp -d $dst_ip --dport $dst_port -j SNAT --to-source $src_ip >/dev/null 2>&1
 		fi
-	done
+	done <<< "$login_port_forward_list"
 	unset port_forward
 }
 
@@ -1361,13 +1474,12 @@ function set_ip_black(){
 	[ -z "$nftables_version" ] && fw_info_blacklistv6=$(ipset list wechatpush_blacklistv6 | grep "timeout" 2>/dev/null)
 
 	fw_info_blacklist="${fw_info_blacklist}\n${fw_info_blacklistv6}"
-	IFS=$'\n'
-	for ip_black_info in $(printf "%b" "$fw_info_blacklist"); do
+	while IFS= read -r ip_black_info; do
 		ip_black=$(echo "$ip_black_info"|grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")
 		[ -z "$ip_black" ] && ip_black=$(echo "$ip_black_info"|grep -Eo "([\da-fA-F0-9]{1,4}(:{1,2})){1,15}[\da-fA-F0-9]{1,4}")
 		[ -z "$ip_black" ] && continue
 		cat ${ip_blacklist_path}|grep -q -w -i ${ip_black} && sed -i "/^${ip_black}/d" ${ip_blacklist_path} && echo ${ip_black_info} >> ${ip_blacklist_path} || del_ip_black ${ip_black}
-	done
+	done <<< "$fw_info_blacklist"
 }
 
 # 发送定时数据
@@ -1375,7 +1487,7 @@ function send(){
 	echo "`date "+%Y-%m-%d %H:%M:%S"` 【定时数据】创建定时任务" >> ${logfile}
 	disturb;local send_disturb=$?
 	get_config "send_title" "send_notification"
-	
+
 	cpuload=`getcpu`
 	service_status=$(ubus call service list '{"name": "wechatpush"}' | grep -o '"running": true')
 	[ -z "$1" ] && ( echo "$send_notification"|grep -q "client_list" ) && > ${dir}send_enable.lock && [ -z "$service_status" ] && first &
@@ -1387,7 +1499,7 @@ function send(){
 		systeminfo_enable="1"
 	fi
 	[ -z "$1" ] && ( echo "$send_notification"|grep -q "router_temp" ) && soc_temp > "$output_dir/cputemp" &
-	
+
 	if [ -z "$1" ] && ( echo "$send_notification"|grep -q "wan_info" ); then
 		getip wanipv4 > "$output_dir/send_wanIP" &
 		getip hostipv4|jq -r '.IP' > "$output_dir/send_hostIP" &
@@ -1400,9 +1512,12 @@ function send(){
 		getinterfaceuptime > "$output_dir/interfaceuptime" &
 	fi
 
+	#[ -z "$1" ] && ( echo "$send_notification"|grep -q "disk_info" ) && get_disk &
+	[ -z "$1" ] && get_disk &
+
 	[ -z "$send_title" ] && send_title="路由状态："
 	[ ! -z "$1" ] && send_title="发送测试：" && send_content="${str_splitline}${str_title_start}内容1${str_title_end}${str_linefeed}${str_tab}设备1${str_linefeed}${str_tab}设备2${str_splitline}${str_title_start}内容2${str_title_end}${str_linefeed}${str_tab}设备3${str_linefeed}${str_tab}设备4"
-	
+
 	wait_and_cat
 	if [ -n "$systeminfo_enable" ]; then
 		[[ $Qwai -eq 200 || $Qwai -eq 301 || $Qwai -eq 302 ]] && Qwai_status="已连通！" || Qwai_status="已断开！"
@@ -1419,16 +1534,35 @@ function send(){
 		[ -z "$cputemp" ] && send_content="${send_content}${str_splitline}${str_title_start} 设备温度${str_title_end}${str_linefeed}${str_tab}无法获取设备温度"
 	fi
 
+	#if [ -z "$1" ] && ( echo "$send_notification"|grep -q "disk_info" ); then
+	if [ -z "$1" ]; then
+		send_content="${send_content}${get_disk}"
+	fi
+
 	if [ -n "$waninfo_enable" ]; then
-		send_content="${send_content}${str_splitline}${str_title_start} WAN 口信息${str_title_end}${str_linefeed}${str_tab}接口 IPv4:${send_wanIP}"
-		send_content="${send_content}${str_linefeed}${str_tab}外网 IPv4:${send_hostIP}"
+		send_content="${send_content}${str_splitline}${str_title_start} WAN 口信息${str_title_end}"
+		if [ "$send_wanIP" == "$send_hostIP" ]; then
+			send_content="${send_content}${str_linefeed}${str_tab}IPv4: ${send_wanIP}"
+		elif [ "$get_ipv4_mode" -eq "1" ]; then
+			send_content="${send_content}${str_linefeed}${str_tab}接口 IPv4: ${send_wanIP}"
+			[ -n "$send_hostIP" ] && send_content="${send_content}${str_linefeed}${str_tab}外网 IPv4: ${send_hostIP}"
+		elif [ "$get_ipv4_mode" -eq "2" ]; then
+			[ -n "$send_wanIP" ] && send_content="${send_content}${str_linefeed}${str_tab}接口 IPv4: ${send_wanIP}"
+			send_content="${send_content}${str_linefeed}${str_tab}外网 IPv4: ${send_hostIP}"
+		fi
 		if [ -n "$ipv6_enable" ]; then
-			send_content="${send_content}${str_linefeed}${str_tab}接口 IPv6:${send_wanIPv6}"
-			send_content="${send_content}${str_linefeed}${str_tab}外网 IPv6:${send_hostIPv6}"
+			if [ "$send_wanIPv6" == "$send_hostIPv6" ]; then
+				send_content="${send_content}${str_linefeed}${str_tab}IPv6: ${send_wanIPv6}"
+			elif [ "$get_ipv6_mode" -eq "1" ]; then
+				send_content="${send_content}${str_linefeed}${str_tab}接口 IPv6: ${send_wanIPv6}"
+				[ -n "$send_hostIPv6" ] && send_content="${send_content}${str_linefeed}${str_tab}外网 IPv6: ${send_hostIPv6}"
+			elif [ "$get_ipv6_mode" -eq "2" ]; then
+				[ -n "$send_wanIPv6" ] && send_content="${send_content}${str_linefeed}${str_tab}接口 IPv6: ${send_wanIPv6}"
+				send_content="${send_content}${str_linefeed}${str_tab}外网 IPv6: ${send_hostIPv6}"
+			fi
 		fi
 		interfaceuptime=`getinterfaceuptime`
 		[ ! -z "$interfaceuptime" ] && wanstatustime=$(printf "在线时间：%d天%d时%d分%d秒" $((interfaceuptime / 86400)) $(((interfaceuptime % 86400) / 3600)) $(((interfaceuptime % 3600) / 60)) $((interfaceuptime % 60)))
-		( ! echo "$send_wanIP"|grep -q -w ${send_hostIP} ) && send_content="${send_content}${str_linefeed}${str_tab}外网 IP 与接口 IP 不一致，你的 IP 可能不是公网 IP"
 		send_content="${send_content}${str_linefeed}${str_tab}${wanstatustime}"
 	fi
 
@@ -1595,6 +1729,9 @@ while [ "$enable" -eq "1" ]; do
 
 	# CPU 检测
 	[ ! -f "${dir}send_enable.lock" ] && cpu_load
+
+	# 硬盘检测
+	#[ ! -f "${dir}send_enable.lock" ] && get_disk
 
 	# 异常流量检测
 	[ ! -f "${dir}send_enable.lock" ] && get_client_usage
